{% set name = "weasel" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b129b44c90cc543b760532974ca1e4eb30dad2aa2026f57bdce66354ae610fc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - weasel = weasel.cli:app
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - confection >=1.0.0
    - packaging >=20.0
    - wasabi >=0.9.1
    - srsly >=2.4.3
    - typer >=0.3.0
    - cloudpathlib >=0.7.0
    - smart_open >=5.2.1
    - httpx >=0.24.0
    - pydantic >=2.0.0

{% set deselect_tests = "" %}
# "[E501] Can not execute command 'touch abc.txt'" on Windows
{% set deselect_tests = deselect_tests + " --deselect=tests/cli/test_cli_app.py::test_project_run" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/cli/test_cli_app.py::test_project_push_pull" %}  # [win]
# Test issue: expects ConfigValidationError but confection raises InterpolationMissingOptionError
# for missing ${vars.b.e}. Fails on all platforms.
{% set skipped_tests = 'not test_project_config_interpolation' %}

test:
  imports:
    - weasel
    - weasel.cli
    - weasel.util
  requires:
    - pip
    - pytest
    - requests
    - git
  commands:
    - pip check
    - weasel --help
    - python -m pytest --tb=native --pyargs {{ name }} -k "{{ skipped_tests }}" {{ deselect_tests }}

about:
  home: https://github.com/explosion/weasel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small and easy workflow system
  description: |
    Weasel lets you manage and share end-to-end workflows for different use
    cases and domains, and orchestrate training, packaging and serving your
    custom pipelines.
  doc_url: https://github.com/explosion/weasel
  dev_url: https://github.com/explosion/weasel

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
