{% set name = "weasel" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6471428ba21064dcdecdd769ce5033034bcd97fbdcf35fa05a32a9dec7cff1ca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - weasel = weasel.cli:app

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - confection >=0.0.4,<0.2.0
    - packaging >=20.0
    - wasabi >=0.9.1,<1.2.0
    - srsly >=2.4.3,<3.0.0
    - catalogue >=2.0.6,<2.1.0
    - typer >=0.3.0,<0.8.0
    - cloudpathlib >=0.7.0,<0.16.0
    - smart-open >=5.2.1,<7.0.0
    - requests >=2.13.0,<3.0.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0

test:
  imports:
    - {{ name }}
  requires:
    - pytest
    - git
    - pip
    - requests
  commands:
    - pip check
    - weasel --help
    - python -m pytest --tb=native --pyargs {{ name }}


about:
  home: https://github.com/explosion/weasel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small and easy workflow system
  description: |
    Weasel lets you manage and share end-to-end workflows for different use
    cases and domains, and orchestrate training, packaging and serving your
    custom pipelines.
  doc_url: https://github.com/explosion/weasel
  dev_url: https://github.com/explosion/weasel

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
