{% set name = "weasel" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f293d6174398e8f478c78481e00c503ee4b82ea7a3e6d0d6a01e46a6b1396845

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - weasel = weasel.cli:app
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - confection >=0.0.4,<0.2.0
    - packaging >=20.0
    - wasabi >=0.9.1,<1.2.0
    - srsly >=2.4.3,<3.0.0
    - typer-slim >=0.3.0,<1.0.0
    - cloudpathlib >=0.7.0,<1.0.0
    - smart_open >=5.2.1,<8.0.0
    - requests >=2.13.0,<3.0.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0

{% set deselect_tests = "" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/cli/test_cli_app.py::test_project_run" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/cli/test_cli_app.py::test_project_push_pull" %}  # [win]

test:
  imports:
    - {{ name }}
  requires:
    - pip
    - pytest
    - requests
  commands:
    - pip check
    - weasel --help
    # test_project_git requires git
    - python -m pytest --tb=native --pyargs {{ name }} -k "not test_project_git" {{ deselect_tests }}

about:
  home: https://github.com/explosion/weasel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small and easy workflow system
  description: |
    Weasel lets you manage and share end-to-end workflows for different use
    cases and domains, and orchestrate training, packaging and serving your
    custom pipelines.
  doc_url: https://github.com/explosion/weasel
  dev_url: https://github.com/explosion/weasel

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd